---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: status

"on":
  workflow_dispatch:
  schedule:
    - cron:  "30 5 * * *"

permissions:
  contents: write

jobs:
  status:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write"}

      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Write date
        run: date >| .github/STATUS

      - name: Execute script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec scripts/generate-status

      - name: Commit changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: STATUS.md .github/STATUS
          message: "docs: automated status update [skip ci]"
          push: true
          commit: --signoff

...
